accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.loginUser, name='login')
]

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('create/', views.create, name='create'),
    path('<int:pk>/upvote/', views.upvote, name='upvote'),
    path('<int:pk>/downvote/', views.downvote, name='downvote')
]

redditclone/urls.py
from django.contrib import admin
from django.urls import path, include

from posts import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('accounts/', include('accounts.urls')),
    path('posts/', include('posts.urls'))
]

accounts/models.py
from django.db import models

# Create your models here.

posts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Post(models.Model):
    title = models.CharField(max_length=200)
    url = models.TextField()
    pub_date = models.DateTimeField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    votes_total = models.IntegerField(default=1)

    def __str__(self):
        return self.title

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login

# Create your views here.


def signup(req):
    if req.method == 'POST':
        if req.POST['password1'] == req.POST['password2']:
            try:
                user = User.objects.get(username=req.POST['username'])
                return render(req, 'accounts/signup.html', {'error': 'Username is already taken!'})
            except User.DoesNotExist:
                user = User.objects.create_user(
                    req.POST['username'], password=req.POST['password1'])
                login(req, user)
                return render(req, 'accounts/signup.html')
        else:
            return render(req, 'accounts/signup.html', {'error': 'Passwords are not matching!'})
    else:
        return render(req, 'accounts/signup.html')


def loginUser(req):
    if req.method == 'POST':
        user = authenticate(
            req, username=req.POST['username'], password=req.POST['password'])
        if user is not None:
            login(req, user)
            if 'next' in req.POST:
                return redirect(req.POST['next'])
            return render(req, 'accounts/login.html', {'error': 'Logged in successfully! ' + req.POST['username']})
        else:
            return render(req, 'accounts/login.html', {'error': 'Username or password is incorrect!'})
    else:
        return render(req, 'accounts/login.html')

posts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from .models import Post

# Create your views here.


@login_required
def create(req):
    if req.method == 'POST':
        if req.POST['title'] and req.POST['url']:
            post = Post()
            post.title = req.POST['title']
            if req.POST['url'].startswith('http://') or req.POST['url'].startswith('https://'):
                post.url = req.POST['url']
            else:
                post.url = 'http://' + req.POST['url']
            post.pub_date = timezone.datetime.now()
            post.author = req.user
            post.save()
            return redirect('home')
        else:
            return render(req, 'posts/create.html', {'error': 'ERROR: You must include a title and URL'})
    else:
        return render(req, 'posts/create.html')


def home(req):
    posts = Post.objects.order_by('-votes_total')
    return render(req, 'posts/home.html', {'posts': posts})


def upvote(req, pk):
    post = Post.objects.get(pk=pk)
    post.votes_total += 1
    post.save()
    return redirect('home')


def downvote(req, pk):
    post = Post.objects.get(pk=pk)
    post.votes_total -= 1
    post.save()
    return redirect('home')

accounts/templates/accounts/login.html
<h1>Log In!</h1>



<form method="POST" action="{% url 'accounts:login' %}">
  {% csrf_token %}



  <h4>Username:</h4>
  <input type='text' name='username' />
  <h4>Password:</h4>
  <input type='password' name='password' />
  <br />
  <br />
  <input type='hidden' name='next' value={{request.GET.next}} />
  <input type='submit' value='Log in!' />
</form>

{% if error %}
{{error}}
{% endif %}

accounts/templates/accounts/signup.html
<h1>Sign Up!</h1>



<form method="POST" action="{% url 'accounts:signup' %}">
  {% csrf_token %}
  <h4>Username:</h4>
  <input type='text' name='username' />
  <h4>Password:</h4>
  <input type='password' name='password1' />
  <h4>Confirm Password:</h4>
  <input type='password' name='password2' />
  <br />
  <br />
  <input type='submit' value='Sign Up!' />
</form>

{% if error %}
{{error}}
{% endif %}

posts/templates/posts/create.html
<h1>Create post!</h1>



<form method="POST" action="{% url 'posts:create' %}">
  {% csrf_token %}



  <h4>Title:</h4>
  <input type='text' name='title' />
  <h4>URL:</h4>
  <input type='text' name='url' />
  <br />
  <br />
  <input type='hidden' name='next' value={{request.GET.next}} />
  <input type='submit' value='Post!' />
</form>

{% if error %}
{{error}}
{% endif %}

posts/templates/posts/home.html
<h1>The Front Page of the Homepage!</h1>
<a href="{% url 'posts:create' %}">Create new Post</a>

<br />
<br />

{% for post in posts.all %}
<a href="{% url 'posts:upvote' pk=post.id %}">+</a>{{post.votes_total}}<a href="{% url 'posts:downvote' pk=post.id %}">-</a>
<a href="{{ post.url }}">{{post.title}}</a>
<br />
{{post.pub_date}} by {{post.author.username}}
<br />
<br />

{% endfor %}